🔧 (CI.yml): update CI workflow to include specific paths for triggering workflow runs on changes in '.github' and 'scaffold-op' directories 🔧 (CI.yml): improve indentation and formatting for better readability and consistency in the script block

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -4,10 +4,15 @@ on:
     push:
         branches:
             - main
+        paths:
+            - '.github/**'
+            - 'scaffold-op/**'
     pull_request:
         branches:
             - main
-
+        paths:
+            - '.github/**'
+            - 'scaffold-op/**'
 jobs:
     build-and-test:
         runs-on: ubuntu-latest
@@ -24,14 +29,14 @@ jobs:
               run: |
                   container_id=$(docker ps -aqf "name=scaffold-test")
                   if [ -z "$container_id" ]; then
-                  	echo "::error::Failed to get the scaffold-test container ID"
+                      echo "::error::Failed to get the scaffold-test container ID"
                   else
-                  	exit_code=$(docker inspect -f '{{.State.ExitCode}}' $container_id)
-                  	echo "Test container exit code: $exit_code"
-                  	if [ "$exit_code" != "0" ]; then
-                  		echo "::error::Tests failed"
-                  		exit 1
-                  	fi
+                      exit_code=$(docker inspect -f '{{.State.ExitCode}}' $container_id)
+                      echo "Test container exit code: $exit_code"
+                      if [ "$exit_code" != "0" ]; then
+                          echo "::error::Tests failed"
+                          exit 1
+                      fi
                   fi
 
             - name: Get scaffold-test logs
