✅ (CI.yml): improve error handling and reporting in the Test containers job to provide more detailed information in case of test failures.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -18,7 +18,18 @@ jobs:
                   fetch-depth: 0
 
             - name: Test containers
-              run: docker compose -f "docker-compose-test.yml" up --build
+              run: |
+                  docker compose -f "docker-compose-test.yml" up --build
+                  container_id=$(docker ps -aqf "name=scaffold-test")
+                  if [ -z "$container_id" ]; then
+                      echo "::error::Failed to get the scaffold-test container ID"
+                  else
+                      exit_code=$(docker inspect -f '{{.State.ExitCode}}' $container_id)
+                      echo "Test container exit code: $exit_code"
+                      if [ "$exit_code" != "0" ]; then
+                      echo "::error::Tests failed"
+                      exit 1
+                  fi
 
             - name: Get scaffold-test logs
               run: docker compose -f "docker-compose-test.yml" logs scaffold-test
